create sequence hibernate_sequence start 1 increment 1;

create table authors (
    id int8 generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    primary key (id));

create table books (
    id int8 generated by default as identity,
    isbn varchar(255) not null,
    user_id int8,
    primary key (id));

create table library_users (
    id int8 generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    address varchar(255) not null,
    primary key (id));

alter table if exists books
    add constraint user_id_books_fk
    foreign key (user_id) references library_users;